//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEDETAIL
    {
        public decimal EMPID { get; set; }
        public string EMPNAME { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public string EMAILID { get; set; }
        public string GENDER { get; set; }
        public string ADDRESS { get; set; }
        public string PINCODE { get; set; }
    }
}
